name: build
on:
  push:
    branches:
      - ci

jobs:
  x86_64-gnu_linux:
    runs-on: ubuntu-latest

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Build---#
      - name: build
        run: ./x86_64-gnu_linux-build.sh

      #---Run---#
      - name: run unittest
        run: ./out/x86_64-gnu_linux-unittest
      - name: run tuto0
        run: ./out/x86_64-gnu_linux-tuto0

  x86_64-macos:
    runs-on: macos-12

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Build---#
      - name: build
        run: ./x86_64-macos-build.command

      #---Run---#
      - name: run unittest
        run: ./out/x86_64-macos-unittest
      - name: run tuto0
        run: ./out/x86_64-macos-tuto0

  x86_64-mingw:
    runs-on: windows-latest

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Download mingw---#
      - name: download mingw
        if: ${{ true }}
        run: |
          cmake -E make_directory ./mingw
          Invoke-WebRequest -OutFile ./mingw/mingw.7z https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-win32-seh-msvcrt-rt_v11-rev0.7z
          cmake -E chdir ./mingw 7z x ./mingw.7z

      #---Build---#
      - name: build
        env:
          MINGW_HOME64: mingw\mingw64
        run: cmd /C x86_64-mingw-build.bat

      #---Run---#
      - name: run unittest
        run: out\x86_64-mingw-unittest
      - name: run tuto0
        run: out\x86_64-mingw-tuto0

  x86_64-windows:
    runs-on: windows-latest

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Configure Visual Studio environment---#
      - name: configure
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      #---Build---#
      - name: build
        run: cmd /C x86_64-windows-build.bat

      #---Run---#
      - name: run unittest
        run: out\x86_64-windows-unittest
      - name: run tuto0
        run: out\x86_64-windows-tuto0
