name: build
on:
  push:
    branches:
      - ci

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Build---#
      - name: build
        run: ./x86_64-gnu_linux-build.sh

      #---Run---#
      - name: run unittest
        run: ./out/x86_64-gnu_linux-unittest
      - name: run tuto0
        run: ./out/x86_64-gnu_linux-tuto0

  mac-build:
    runs-on: macos-12

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Build---#
      - name: build
        run: ./x86_64-macos-build.command

      #---Run---#
      - name: run unittest
        run: ./out/x86_64-macos-unittest
      - name: run tuto0
        run: ./out/x86_64-macos-tuto0

  windows-build-x64:
    runs-on: windows-latest

    steps:
      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v4

      #---Configure Visual Studio environment---#
      - name: configure
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      #---Build---#
      - name: build
        run: cmd /C x86_64-windows-build.bat

      #---Run---#
      - name: run unittest
        run: out\x86_64-windows-unittest
      - name: run tuto0
        run: out\x86_64-windows-tuto0
